### ISSUE TITLE
No active prediction in demo

### ISSUE THREAD

**Issue by stefanspirkl** [sirko-io/engine#44]
FYI - https://demo.sirko.io/home does not seem to generate predictions when navigating the demo site.

This very likely is an issue with the stats connected to the demo instance, not an issue in the source itself.

**Comment by dnesteryuk** [comment]
@stefanspirkl thanks for letting me know! :+1:  It was an issue with a SSL certificate :slightly_frowning_face:

**Comment by stefanspirkl** [comment]
Thanks for the update Dmitriy, I can confirm predictions are now generated and the issue can be marked resolved
